name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'  # 每半小时运行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Sync all branches
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote add upstream https://github.com/BartoszCichecki/LenovoLegionToolkit
          git fetch upstream
          for branch in $(git branch -r | grep 'upstream/' | sed 's/upstream\///'); do
            if [ "$branch" != "HEAD" ]; then
              git checkout $branch || git checkout -b $branch
              git merge upstream/$branch
              git push origin $branch
            fi
          done
